---
# tasks file for roles/workstation

#
# Additional packages
#

- name: "Installing additional packages"
  dnf:
    name:
      - git
      - flatpak
      - gimp
#      - google-chrome-stable
      - gnome-terminal-nautilus
      - gnome-tweak-tool
      - htop
      - levien-inconsolata-fonts
      - ranger
      - tmux
      - fish
      - util-linux
    state: present

# Shell
- name: Update default shell to fish
  user:
    name: docker
    shell: /usr/bin/fish
    append: yes

# icc brightness

- name: "Installing package for icc-brightness"
  dnf:
    name:
      - lcms2-devel
      - make
      - gcc
    state: present

- git:
    repo: 'https://github.com/udifuchs/icc-brightness.git'
    dest: /tmp/icc-brightness


- name: Build the default target
  make:
    chdir: /tmp/icc-brightness

- name: Run 'install' target as root
  make:
    chdir:  /tmp/icc-brightness
    target: install
  become: yes

# Install brave

- name: Add Brave repository
  yum_repository:
    name: brave
    description: Brave RPM repository
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/

- name: Importing rpm-gpg key from brave
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: "Installing package for brave"
  dnf:
    name:
      - brave-browser
    state: present

# Flatpak

# - name: Add the Gnome flatpak remote to the system installation
#   flatpak_remote:
#     name: gnome
#     state: present
#     flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install spotify from flathub
  flatpak:
    name: com.spotify.Client
    state: present

- name: Install slack from flathub
  flatpak:
    name: com.slack.Slack
    state: present

- name: Install discord from flathub
  flatpak:
    name: com.discordapp.Discord
    state: present

# SSH keys
- name: Create a 2048-bit SSH key for user agravelot in ~agravelot/.ssh/id_rsa
  user:
    name: agravelot
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


# Docker
- name: Cleanup conflicts package with docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Add Docker repo
  get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Change docker repository version to 31 unitl 32 released
  replace:
    path: /etc/yum.repos.d/docker-ce.repo
    regexp: '\$releasever'
    replace: '31'

- name: "Installing docker"
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Make sure docker service is running
  systemd:
    state: started
    name: docker
    enabled: yes

- name: Add user agravelot to docker group
  user:
    name: agravelot
    groups: docker
    append: yes


